version: "3.1"

services:
  db:
    container_name: corelab_database
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=corelab
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "3333:5432"

  api:
    container_name: backend_aplication
    build:
      context: ../todo_list_back/
    depends_on:
      - db
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ../todo_list_back:/usr/app
    command: sh -c "npm install && npm run typeorm migration:run -- -d src/data-source && npm run dev"

  application:
    container_name: web_application
    build:
      context: ../todo_list_front/
    depends_on:
      - api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../todo_list_front:/usr/app
    command: sh -c "npm install && npm run dev"
